[package]
name = "d05"
version = "0.1.0"
authors = ["Kristjan Siimson <k.siimson@sportradar.com>"]
edition = "2021"

[dependencies]
btoi = "0.4"
bitset-fixed = "0.1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false
